#!/bin/bash

if [[ ! -f ~/tips  ]]; then
	curl -s https://raw.githubusercontent.com/jlevy/the-art-of-command-line/master/README.md |
	pandoc -f markdown -t html |
	xmlstarlet fo --html --dropdtd  > ~/tips 
fi

cat ~/tips |
 xmlstarlet sel -t -v "(html/body/ul/li[count(p)>0])[$RANDOM mod last()+1]" |
 xmlstarlet unesc |
 fmt -80
